### ISSUE TITLE
setting args not work

### ISSUE THREAD

**Issue by sytolk** [theproductiveprogrammer/pm2#17]
Hello,
I've try to set arguments to the script: https://github.com/theproductiveprogrammer/pm2#passing-arguments-to-scripts
but args is not set. I see that there is PR (closed) for this: https://github.com/theproductiveprogrammer/pm2/pull/12
Is this project maintained?

**Comment by theproductiveprogrammer** [comment]
Hi - I must have missed PR #12. Will accept it now. Thank you @sytolk

**Comment by theproductiveprogrammer** [comment]
Hmmm... that PR is closed. I've asked the owner @giacco to re-open to accept his fix.

**Comment by giacco** [comment]
Hi, I have created a new PR #18 .
Is the same as #12 , I just added args on start function

**Comment by theproductiveprogrammer** [comment]
Thanks @giacco & @sytolk. Will close this issue now.

**Comment by sytolk** [comment]
Thanks @theproductiveprogrammer but maybe env is missing too: https://github.com/theproductiveprogrammer/pm2#setting-the-environment
here: https://github.com/theproductiveprogrammer/pm2/blob/master/index.js#L52

**Comment by theproductiveprogrammer** [comment]
Good catch @sytolk . Have fixed in PR #19 and updated the test cases to check. Thanks!!
